Repository WildCodeSchool-2024-02/toulouse-geocode, pull requests merged in 2024-07, with the labels that each got.

#37 S5 us48/3d map
  client/index.html
  client/package.json
  client/src/main.jsx
  client/src/pages/Map.jsx
  client/src/pages/MapPage.jsx
  client/src/pages/MapPage.scss
  package-lock.json
Labels: CORRECTIONS DONE

#38 feat: add a real uncluster animation
  client/package.json
  client/src/components/BackButton.jsx
  client/src/components/Modal.jsx
  client/src/pages/ContactForm.jsx
  client/src/pages/MapPage.jsx
  client/src/pages/MapPage.scss
Labels: REVIEWED

#39 S3 us19/inscription page
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/main.jsx
  client/src/pages/Connect.jsx
  client/src/pages/Form.scss
  client/src/pages/MapPage.jsx
  client/src/pages/Register.jsx
  client/src/pages/Register.scss
  package-lock.json
  server/app/config.js
  server/app/controllers/userActions.js
  server/app/routers/api/users/router.js
  server/app/services/auth.js
  server/app/services/hashPassword.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEWED

#40 feat: add toast on login and register
  client/package.json
  client/src/pages/Connect.jsx
  client/src/pages/Register.jsx
  server/package.json
Labels: REVIEWED

#41 S5 us64/navbar
  client/package.json
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/pages/Connect.jsx
  client/src/pages/ContactForm.jsx
  client/src/pages/Home.scss
  client/src/pages/MapPage.jsx
  client/src/pages/Register.jsx
  server/app/services/auth.js
Labels: REVIEWED

#42 feat: add dynamique geolocate system
  client/src/pages/MapPage.jsx
  package-lock.json
Labels: REVIEWED

#43 S5 us63/toast notifications
  client/src/components/Navbar.scss
  client/src/pages/Connect.jsx
  client/src/pages/MapPage.jsx
  client/src/pages/Register.jsx
  server/.env.sample
Labels: REVIEWED

#44 fix: css of home logo
  client/src/components/Navbar.scss
Labels: REVIEWED

#45 Dev
  client/index.html
  client/package.json
  client/src/components/BackButton.jsx
  client/src/components/Modal.jsx
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/main.jsx
  client/src/pages/Connect.jsx
  client/src/pages/ContactForm.jsx
  client/src/pages/Form.scss
  client/src/pages/Home.scss
  client/src/pages/Map.jsx
  client/src/pages/MapPage.jsx
  client/src/pages/MapPage.scss
  client/src/pages/Register.jsx
  client/src/pages/Register.scss
  package-lock.json
  server/.env.sample
  server/app/config.js
  server/app/controllers/userActions.js
  server/app/routers/api/users/router.js
  server/app/services/auth.js
  server/app/services/hashPassword.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/package.json
Labels: REVIEWED

#46 fix: change JWT_SECRET to APP_SECRET
  server/.env.sample
  server/app/controllers/userActions.js
Labels: REVIEWED

#47 fix: map css inline
  client/src/pages/MapPage.jsx
Labels: REVIEWED

#48 Dev
  client/src/pages/MapPage.jsx
  server/.env.sample
  server/app/controllers/userActions.js
Labels: REVIEWED

#50 S5 us48/3d map
  client/public/tab.geojson
  client/src/components/PopupCard.jsx
  client/src/components/PopupCard.scss
  client/src/pages/Connect.jsx
  client/src/pages/ContactForm.jsx
  client/src/pages/MapPage.jsx
  client/src/pages/MapPage.scss
  client/src/pages/Register.jsx
  client/src/style/button.scss
  client/src/style/colors.scss
  client/src/style/input.scss
  client/src/style/style.scss
  package-lock.json
  server/app/routers/api/users/router.js
  server/database/models/ChargingStationRepository.js
Labels: CONFLICTS RESOLVED, REVIEWED

#51 S5 us64/navbar
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/pages/MapPage.jsx
Labels: REVIEWED

#52 feat: add front and back filter system for plus type with protection …
  client/src/components/DropdownSelector.jsx
  client/src/constants/plugsList.js
  client/src/main.jsx
  client/src/pages/MapPage.jsx
  client/src/utils/useFetchData.jsx
  server/app/controllers/chargingStationActions.js
  server/app/routers/api/chargingStations/router.js
  server/app/services/formatQuery.js
  server/database/models/ChargingStationRepository.js
Labels: REVIEWED

#53 feat: filter back and front for pagination system
  client/src/utils/useFetchData.jsx
  server/app/controllers/chargingStationActions.js
  server/app/routers/api/chargingStations/router.js
  server/app/services/formatQuery.js
  server/database/models/ChargingStationRepository.js
Labels: REVIEW REQUESTED

#54 S5 us64/plug
  client/public/plugchade.svg
  client/public/plugcombo.svg
  client/public/plugtype2.svg
  client/src/main.jsx
  client/src/pages/Plug.jsx
  client/src/pages/Plug.scss
Labels: REVIEWED

#55 S5 us64/navbar
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/style/style.scss
Labels: REVIEWED

#56 S5 us64/navbar
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
Labels: REVIEWED

#59 S6 us00/beta build
  client/index.html
  client/package.json
  client/src/components/AdminChargingStations.jsx
  client/src/components/AdminMessage.jsx
  client/src/components/AdminPersonnalInfo.jsx
  client/src/components/AdminReservations.jsx
  client/src/components/AdminUser.jsx
  client/src/components/DropdownSelector.jsx
  client/src/components/FilteringMenu.jsx
  client/src/components/FilteringMenu.scss
  client/src/components/Hud.jsx
  client/src/components/Hud.scss
  client/src/components/LoginButton.jsx
  client/src/components/LogoutButton.jsx
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/components/PopupCard.jsx
  client/src/components/ReservationDateSelector.jsx
  client/src/components/ReservationDateSelector.scss
  client/src/context/AuthContext.jsx
  client/src/main.jsx
  client/src/pages/AdminBackOffice.jsx
  client/src/pages/AdminBackOffice.scss
  client/src/pages/Connect.jsx
  client/src/pages/ContactForm.jsx
  client/src/pages/Home.jsx
  client/src/pages/Home.scss
  client/src/pages/MapPage.jsx
  client/src/pages/MapPage.scss
  client/src/pages/Register.jsx
  client/src/pages/Register.scss
  client/src/pages/UserProfil.jsx
  client/src/pages/UserProfil.scss
  client/src/pages/userProfile.jsx
  client/src/services/utils.js
  client/src/style/style.scss
  client/src/utils/useAuth.jsx
  client/src/utils/useFetchData.jsx
  client/src/utils/useLocalStorage.jsx
  client/src/utils/useUser.jsx
  package-lock.json
  server/app/config.js
  server/app/controllers/chargingStationActions.js
  server/app/controllers/reservationActions.js
  server/app/controllers/userActions.js
  server/app/routers/api/chargingStations/router.js
  server/app/routers/api/reservation/router.js
  server/app/routers/api/router.js
  server/app/routers/api/users/router.js
  server/app/services/auth.js
  server/app/services/formatQuery.js
  server/database/models/ChargingStationRepository.js
  server/database/models/ReservationRepository.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/database/tables.js
Labels: REVIEWED

#61 S6 us48/book front
  client/src/components/FilteringMenu.jsx
  client/src/components/Navbar.jsx
  client/src/components/PopupCard.jsx
  client/src/main.jsx
  client/src/pages/MapPage.jsx
  client/src/pages/Reservation.jsx
  server/app/routers/api/reservation/router.js
Labels: REVIEW REQUESTED

#62 S6 us48/hud
  client/src/components/FilteringMenu.jsx
  client/src/components/FilteringMenu.scss
  client/src/components/Hud.jsx
  client/src/components/Hud.scss
  client/src/components/Navbar.jsx
  client/src/components/Navbar.scss
  client/src/components/PopupCard.jsx
  client/src/pages/Connect.jsx
  client/src/pages/Connect.scss
  client/src/pages/Form.scss
  client/src/pages/MapPage.jsx
  client/src/pages/MapPage.scss
  client/src/pages/Reservation.jsx
  client/src/pages/Reservation.scss
  client/src/style/style.scss
Labels: REVIEW REQUESTED

#63 S7 us68/front reservation
  client/src/components/PopupCard.jsx
  client/src/pages/Reservation.jsx
  client/src/pages/Reservation.scss
  client/src/services/utils.js
  client/src/style/button.scss
Labels: REVIEWED

#69 fix: remove localhost
  client/src/pages/MapPage.jsx
Labels: REVIEWED

#70 Dev
  client/src/pages/MapPage.jsx
Labels: REVIEWED

#71 fix: fix
  client/src/pages/UserProfil.jsx
  server/app/controllers/vehicleActions.js
  server/database/models/VehicleRepository.js
  server/database/schema.sql
Labels: REVIEWED

#74 fix: another fix, give me that
  client/src/components/Hud.jsx
  client/src/components/Navbar.jsx
Labels: REVIEWED
